var CACHE_NAME = 'static-v1'

self.addEventListener('install', function(event){
    event.waitUntil(
        caches.open(CACHE_NAME).then(function(cache){
            return cache.addAll([
                '/',
                '/index.html',
                '/index.css',
                '/index.js',
                '/contacts.html',
                '/loading.gif',
                '/manifest.json',
                '/menu.css',
                '/menu.html',
                '/studies.html',
                '/AtaquEstok/imgs/objects/box.png',
                '/AtaquEstok/imgs/objects/claw.png',
                '/AtaquEstok/imgs/player/player.png',
                '/AtaquEstok/imgs/scenario/bg.png',
                '/AtaquEstok/musics/music1.ogg',
                '/AtaquEstok/musics/music2.ogg',
                '/AtaquEstok/musics/music3.ogg',
                '/AtaquEstok/snds/explosion.wav',
                '/AtaquEstok/snds/explosion2.wav',
                '/AtaquEstok/snds/punch-1.wav',
                '/AtaquEstok/snds/punch-2.wav',
                '/AtaquEstok/AtaquEstok.html',
                '/AtaquEstok/css.css',
                '/AtaquEstok/js.js',
                '/AtaquEstok/load.js',
                '/AtaquEstok/objects.js',
                '/AtaquEstok/preview.js',
                '/fonts/Comic Sans MS.ttf',
                '/fonts/HARNGTON.TTF',
                '/imgs/dj-72.png',
                '/imgs/dj-96.png',
                '/imgs/dj-128.png',
                '/imgs/dj-144.png',
                '/imgs/dj-152.png',
                '/imgs/dj-192.png',
                '/imgs/dj-384.png',
                '/imgs/dj-512.png',
                '/imgs/dj.png',
                '/imgs/djgames.png',
                '/imgs/djGit.png',
                '/imgs/fullScreen.png',
                '/imgs/ico.ico',
                '/imgs/loading.gif',
                '/Invasores/img/inimigos/gray.png',
                '/Invasores/img/inimigos/mini.png',
                '/Invasores/img/inimigos/tiro.png',
                '/Invasores/img/itens/canhao.png',
                '/Invasores/img/itens/escudo (1).png',
                '/Invasores/img/itens/escudo (2).png',
                '/Invasores/img/itens/escudo (3).png',
                '/Invasores/img/itens/escudo (4).png',
                '/Invasores/img/itens/escudo (5).png',
                '/Invasores/img/itens/escudo (6).png',
                '/Invasores/img/itens/escudo (7).png',
                '/Invasores/img/itens/escudo (8).png',
                '/Invasores/img/itens/escudo (9).png',
                '/Invasores/img/itens/escudo (10).png',
                '/Invasores/img/itens/escudo (11).png',
                '/Invasores/img/itens/escudo (12).png',
                '/Invasores/img/itens/escudo (13).png',
                '/Invasores/img/itens/escudo (14).png',
                '/Invasores/img/itens/escudo (15).png',
                '/Invasores/img/itens/escudo (16).png',
                '/Invasores/img/itens/escudo.png',
                '/Invasores/img/itens/escudo2 (1).png',
                '/Invasores/img/itens/escudo2 (2).png',
                '/Invasores/img/itens/escudo2 (3).png',
                '/Invasores/img/itens/escudo2 (4).png',
                '/Invasores/img/itens/escudo2 (5).png',
                '/Invasores/img/itens/escudo2 (6).png',
                '/Invasores/img/itens/escudo2 (7).png',
                '/Invasores/img/itens/escudo2 (8).png',
                '/Invasores/img/itens/escudo2 (9).png',
                '/Invasores/img/itens/escudo2 (10).png',
                '/Invasores/img/itens/escudo2 (11).png',
                '/Invasores/img/itens/escudo2 (12).png',
                '/Invasores/img/itens/escudo2 (13).png',
                '/Invasores/img/itens/escudo2 (14).png',
                '/Invasores/img/itens/escudo2 (15).png',
                '/Invasores/img/itens/escudo2 (16).png',
                '/Invasores/img/itens/metranca.png',
                '/Invasores/img/itens/nvlArma.png',
                '/Invasores/img/itens/tps.png',
                '/Invasores/img/itens/vida.png',
                '/Invasores/img/objetos/estrela (1).png',
                '/Invasores/img/objetos/estrela (2).png',
                '/Invasores/img/objetos/nebulosa (1).png',
                '/Invasores/img/objetos/nebulosa (2).png',
                '/Invasores/img/objetos/nebulosa (3).png',
                '/Invasores/img/objetos/nebulosaFundo (5).png',
                '/Invasores/img/objetos/nebulosaFundo (6).png',
                '/Invasores/img/objetos/planeta (1).png',
                '/Invasores/img/objetos/planeta (2).png',
                '/Invasores/img/objetos/planeta (3).png',
                '/Invasores/img/objetos/planeta (4).png',
                '/Invasores/img/objetos/planeta (5).png',
                '/Invasores/img/objetos/planeta (6).png',
                '/Invasores/img/objetos/sol.png',
                '/Invasores/img/objetos/z (1).png',
                '/Invasores/img/objetos/z (2).png',
                '/Invasores/img/objetos/z (3).png',
                '/Invasores/img/player/movendo (1).png',
                '/Invasores/img/player/movendo (2).png',
                '/Invasores/img/player/movendo (3).png',
                '/Invasores/img/player/movendo (4).png',
                '/Invasores/img/player/movendoC (1).png',
                '/Invasores/img/player/movendoC (2).png',
                '/Invasores/img/player/movendoC (3).png',
                '/Invasores/img/player/movendoC (4).png',
                '/Invasores/img/player/movendoM (1).png',
                '/Invasores/img/player/movendoM (2).png',
                '/Invasores/img/player/movendoM (3).png',
                '/Invasores/img/player/movendoM (4).png',
                '/Invasores/img/player/parado (1).png',
                '/Invasores/img/player/parado (2).png',
                '/Invasores/img/player/parado (3).png',
                '/Invasores/img/player/parado (4).png',
                '/Invasores/img/player/paradoC (1).png',
                '/Invasores/img/player/paradoC (2).png',
                '/Invasores/img/player/paradoC (3).png',
                '/Invasores/img/player/paradoC (4).png',
                '/Invasores/img/player/paradoM (1).png',
                '/Invasores/img/player/paradoM (2).png',
                '/Invasores/img/player/paradoM (3).png',
                '/Invasores/img/player/paradoM (4).png',
                '/Invasores/img/player/tiro.png',
                '/Invasores/img/player/tiroCan.png',
                '/Invasores/img/player/tiroCan2.png',
                '/Invasores/img/player/tiroMet.png',
                '/Invasores/img/explosao.png',
                '/Invasores/img/explosao1.png',
                '/Invasores/img/explosao2.png',
                '/Invasores/img/explosao3.png',
                '/Invasores/img/fundo.png',
                '/Invasores/interface/btContinuar1.png',
                '/Invasores/interface/btContinuar2.png',
                '/Invasores/interface/btContinuar3.png',
                '/Invasores/interface/btJogar1.png',
                '/Invasores/interface/btJogar2.png',
                '/Invasores/interface/btJogar3.png',
                '/Invasores/interface/btSair1.png',
                '/Invasores/interface/btSair2.png',
                '/Invasores/interface/btSair3.png',
                '/Invasores/interface/edit1.png',
                '/Invasores/interface/edit2.png',
                '/Invasores/interface/loading.png',
                '/Invasores/interface/logo.png',
                '/Invasores/interface/menu.png',
                '/Invasores/snd/explode (1).ogg',
                '/Invasores/snd/explode (2).ogg',
                '/Invasores/snd/explode (3).ogg',
                '/Invasores/snd/explode (4).ogg',
                '/Invasores/snd/logo.ogg',
                '/Invasores/snd/loop (1).ogg',
                '/Invasores/snd/tiro (1).ogg',
                '/Invasores/snd/tiro (2).ogg',
                '/Invasores/css.css',
                '/Invasores/Invasores.html',
                '/Invasores/js.js',
                '/Invasores/load.js',
                '/Invasores/magneto.ttf',
                '/Invasores/preview.png',
                '/Quebra Tudo/img/ampBola.png',
                '/Quebra Tudo/img/ampPlayer.png',
                '/Quebra Tudo/img/bloco1.png',
                '/Quebra Tudo/img/bloco2.png',
                '/Quebra Tudo/img/bola.png',
                '/Quebra Tudo/img/coracao.png',
                '/Quebra Tudo/img/fundo.png',
                '/Quebra Tudo/img/player.png',
                '/Quebra Tudo/img/redBola.png',
                '/Quebra Tudo/img/redPlayer.png',
                '/Quebra Tudo/interface/btContinuar1.png',
                '/Quebra Tudo/interface/btContinuar2.png',
                '/Quebra Tudo/interface/btJogar1.png',
                '/Quebra Tudo/interface/btJogar2.png',
                '/Quebra Tudo/interface/btSair1.png',
                '/Quebra Tudo/interface/btSair2.png',
                '/Quebra Tudo/interface/edit1.png',
                '/Quebra Tudo/interface/edit2.png',
                '/Quebra Tudo/interface/loading.png',
                '/Quebra Tudo/interface/logo.png',
                '/Quebra Tudo/snd/croc.ogg',
                '/Quebra Tudo/snd/logo.ogg',
                '/Quebra Tudo/snd/loop (1).ogg',
                '/Quebra Tudo/snd/powerUp.ogg',
                '/Quebra Tudo/snd/toc.ogg',
                '/Quebra Tudo/snd/vida.ogg',
                '/Quebra Tudo/css.css',
                '/Quebra Tudo/js.js',
                '/Quebra Tudo/load.js',
                '/Quebra Tudo/preview.png',
                '/Quebra Tudo/Quebra Tudo.html',
                '/Quebra Tudo/QuebraTudo.ico',
                '/S.i.n.S/imgs/bg1.png',
                '/S.i.n.S/imgs/bg2.png',
                '/S.i.n.S/imgs/bg3.png',
                '/S.i.n.S/imgs/bg4.png',
                '/S.i.n.S/imgs/bg5.png',
                '/S.i.n.S/imgs/bg6.png',
                '/S.i.n.S/imgs/macaVerde.png',
                '/S.i.n.S/imgs/macaVermelha.png',
                '/S.i.n.S/imgs/melancia.png',
                '/S.i.n.S/imgs/uva.png',
                '/S.i.n.S/interface/1-2.png',
                '/S.i.n.S/interface/checked.png',
                '/S.i.n.S/interface/Continuar1.png',
                '/S.i.n.S/interface/Continuar2.png',
                '/S.i.n.S/interface/edit.png',
                '/S.i.n.S/interface/ia1.png',
                '/S.i.n.S/interface/ia2.png',
                '/S.i.n.S/interface/Jogar1.png',
                '/S.i.n.S/interface/Jogar2.png',
                '/S.i.n.S/interface/loading.png',
                '/S.i.n.S/interface/logo.png',
                '/S.i.n.S/interface/menu.png',
                '/S.i.n.S/interface/modo.png',
                '/S.i.n.S/interface/range.png',
                '/S.i.n.S/interface/S.i.n.S.png',
                '/S.i.n.S/interface/Sair1.png',
                '/S.i.n.S/interface/Sair2.png',
                '/S.i.n.S/interface/selVel.png',
                '/S.i.n.S/interface/unchecked.png',
                '/S.i.n.S/sons/die.wav',
                '/S.i.n.S/sons/eat.wav',
                '/S.i.n.S/sons/eat2.wav',
                '/S.i.n.S/sons/eatS.ogg',
                '/S.i.n.S/sons/eatS.wav',
                '/S.i.n.S/sons/logo.ogg',
                '/S.i.n.S/estilo.css',
                '/S.i.n.S/load.js',
                '/S.i.n.S/nodo.js',
                '/S.i.n.S/preview.png',
                '/S.i.n.S/S.i.n.S.html',
                '/S.i.n.S/S.i.n.S.ico',
                '/S.i.n.S/S.i.n.S.png',
                '/S.i.n.S/script.js',
                '/S.i.n.S2/imgs/fundo.png',
                '/S.i.n.S2/imgs/fundoA.png',
                '/S.i.n.S2/imgs/fundoB.png',
                '/S.i.n.S2/imgs/fundoEscuro.png',
                '/S.i.n.S2/imgs/iris.png',
                '/S.i.n.S2/imgs/olhos0.png',
                '/S.i.n.S2/imgs/olhos1.png',
                '/S.i.n.S2/interface/cursor/cur.png',
                '/S.i.n.S2/interface/cursor/cursor.png',
                '/S.i.n.S2/interface/btContinuar1.png',
                '/S.i.n.S2/interface/btContinuar2.png',
                '/S.i.n.S2/interface/btCriar1.png',
                '/S.i.n.S2/interface/btCriar2.png',
                '/S.i.n.S2/interface/btJogar1.png',
                '/S.i.n.S2/interface/btJogar2.png',
                '/S.i.n.S2/interface/btSair1.png',
                '/S.i.n.S2/interface/btSair2.png',
                '/S.i.n.S2/interface/edNome1.png',
                '/S.i.n.S2/interface/edNome2.png',
                '/S.i.n.S2/interface/fundo.png',
                '/S.i.n.S2/interface/range.png',
                '/S.i.n.S2/interface/select.png',
                '/S.i.n.S2/interface/selector1.png',
                '/S.i.n.S2/interface/selector2.png',
                '/S.i.n.S2/interface/setaDir1.png',
                '/S.i.n.S2/interface/setaDir2.png',
                '/S.i.n.S2/interface/setaEsq1.png',
                '/S.i.n.S2/interface/setaEsq2.png',
                '/S.i.n.S2/interface/titulo.png',
                '/S.i.n.S2/sons/logo.ogg',
                '/S.i.n.S2/css.css',
                '/S.i.n.S2/js.js',
                '/S.i.n.S2/load.js',
                '/S.i.n.S2/logo.png',
                '/S.i.n.S2/nomes.js',
                '/S.i.n.S2/preview.png',
                '/S.i.n.S2/S.i.n.S2.html',
                '/S.i.n.S2/sins.js',
                '/Tetris/fonts/bauhaus.ttf',
                '/Tetris/fonts/wingding.ttf',
                '/Tetris/snds/explosion.wav',
                '/Tetris/snds/merge.wav',
                '/Tetris/snds/turn.wav',
                '/Tetris/arena.js',
                '/Tetris/btn.js',
                '/Tetris/css.css',
                '/Tetris/edit.js',
                '/Tetris/js.js',
                '/Tetris/main.js',
                '/Tetris/player.js',
                '/Tetris/preview.png',
                '/Tetris/sounds.js',
                '/Tetris/tetris.html'
            ])
        })
    )
})

self.addEventListener('activate', function activator(event){
    event.waitUntil(
        caches.keys().then(function (keys){
            return Promise.all(keys
                .filter(function (key){
                    return key.indexOf(CACHE_NAME)!==0
                })
                .map(function (key){
                    return caches.delete(key)
                })
            )
        })
    )
})

self.addEventListener('fetch', function(event){
    event.respondWith(
        caches.match(event.request).then(function(cachedResponse){
            return cachedResponse || fetch(event.request)
        })
    )
})