var nomes=[];

nomes.push("Minhocossauro");
nomes.push("Aristóteles");
nomes.push("Anaconda");
nomes.push("Anathsunamoon");
nomes.push("Chuck Norris");
nomes.push("Mario");
nomes.push("Luigi");
nomes.push("Sauron");
nomes.push("Pedro");
nomes.push("Beth");
nomes.push("Creuza");
nomes.push("Lola");
nomes.push("Roberval");
nomes.push("Ária");
nomes.push("Valdemorth");
nomes.push("Oslo");
nomes.push("Bafo");
nomes.push("Alduin");
nomes.push("Dohvakiin");
nomes.push("Parthunax");
nomes.push("Golum");
nomes.push("Ted");
nomes.push("Jhon Snow");
nomes.push("Magaiver");
nomes.push("Hércules");
nomes.push("Xena");
nomes.push("Fica longe!");
nomes.push("Shrek");
nomes.push("Baal");
nomes.push("Chicletão");
nomes.push("Rick");
nomes.push("Morty");
nomes.push("Godzilla");
nomes.push("Ozzy");
nomes.push("Banguela");
nomes.push("Ligeirinho");
nomes.push("Dolores");
nomes.push("Bernard");
nomes.push("Ford");
nomes.push("Anabele");
nomes.push("Samara");
nomes.push("Michone");
nomes.push("Avada");
nomes.push("Kedabra");
nomes.push("Fonoiossa");
nomes.push("Chaplin");
nomes.push("Neni");
nomes.push("Luli");
nomes.push("Nena");
nomes.push("Heitor");
nomes.push("Legolas");
nomes.push("Aragorn");
nomes.push("Gimly");
nomes.push("Patolino");
nomes.push("Margarida");
nomes.push("Desespero");
nomes.push("Soninho");
nomes.push("Ruga");
nomes.push("Minhoca");
nomes.push("Brutus");
nomes.push("Vem que eu te abraço");
nomes.push("Eustácio");
nomes.push("Coragem");
nomes.push("Lady Melisandre");
nomes.push("Locky");
nomes.push("Maninho");
nomes.push("Joe");
nomes.push("Jobelinho das Cove");
nomes.push("Tio Mi");
nomes.push("Rainha das minhocas");
nomes.push("Belinha");
nomes.push("George");
nomes.push("Nega véia");
nomes.push("Não me mate..");
nomes.push("Sindy");
nomes.push("Bad boy");
nomes.push("Oie");
nomes.push("Kid Minhoca");
nomes.push("Cobrinha");
nomes.push("Xamã");
nomes.push("Solitária");
nomes.push("Gaga");
nomes.push("Reinentinha");
nomes.push("Rolz");
nomes.push("Capitão Nascimento");
nomes.push("Poiu");
nomes.push("Qwerty");
nomes.push("Elliot");
nomes.push("Mr. SinS");
nomes.push("Xixo");
nomes.push("Dudu");
nomes.push("Terezinha");
nomes.push("Tyrion");
nomes.push("Jaime");
nomes.push("Girubéba");